/**
 * Cookbook API
 * API endpoints for recipes, authentication, and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenType } from './tokenType';
import { User } from './user';


export interface Token { 
    id?: number;
    token?: string;
    tokenType?: TokenType;
    revoked?: boolean;
    expired?: boolean;
    user?: User;
}
export namespace Token {
}


